name: Run EasyMorph File on Windows

on:
  push:
    paths:
      - '**/*.morph'  # Triggers when any .morph file is pushed
  workflow_dispatch: # Allows manual execution from GitHub Actions UI

jobs:
  run-easymorph:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Execution Policy for PowerShell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process

      - name: Run EasyMorph File
        run: |
          powershell -ExecutionPolicy Bypass -Command "& 'Morph.exe' 'C:\Users\Mandar.Shinde\Repository\EasyMorph\employee_department_table.morph'"