name: Run EasyMorph PowerShell Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-morph:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process

      - name: Run PowerShell Script
        run: |
          & "C:\Users\Mandar.Shinde\Repository\EasyMorph\run-morph.ps1"