name: Run EasyMorph on Local System

on:
  push:
    branches:
      - main  # Trigger only on the main branch

jobs:
  trigger-local-job:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Send Webhook to Local Machine
        run: |
          curl -X POST http://106.215.180.181:8080/ -d '{
            "status": "success",
            "message": "GitHub Action completed"
          }'
