name: EasyMorph CI/CD

on:
  push:
    branches:
      - main  # Trigger on any push to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Notify Local System
        run: |
          $url = "http://106.215.180.181:5000/webhook"
          Invoke-WebRequest -Uri $url -Method Post