name: Run EasyMorph Job

on:
  push:
    branches:
      - main  # Runs workflow when changes are pushed to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-morph:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Fetches the latest code from GitHub

    - name: Set PowerShell Execution Policy
      run: Set-ExecutionPolicy Bypass -Scope Process -Force
      shell: powershell

    - name: Install EasyMorph CLI (If Needed)
      run: |
        if (!(Test-Path "C:\easymorph\morph-cmd.exe")) {
          Invoke-WebRequest -Uri "https://easymorph.com/download/morph-cli.zip" -OutFile "morph-cli.zip"
          Expand-Archive -Path "morph-cli.zip" -DestinationPath "C:\easymorph"
        }
      shell: powershell

    - name: Run EasyMorph Job
      run: |
        C:\easymorph\morph-cmd.exe -file "employee_department_table.morph" -param "ENVIRONMENT=DEV"
      shell: cmd

    - name: Upload Logs (if needed)
      uses: actions/upload-artifact@v4
      with:
        name: morph-logs
        path: C:\easymorph\logs\  # Change to your actual logs path
