name: Run EasyMorph PowerShell Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-morph:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Paths
        run: echo "SCRIPT_PATH=${{ github.workspace }}\EasyMorph\run-morph.ps1" >> $GITHUB_ENV

      - name: Debug: Show Current Directory and Files
        run: |
          echo "Current Directory: $PWD"
          echo "Listing Files..."
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: Ensure Script Exists
        run: |
          if (Test-Path "$env:SCRIPT_PATH") {
            echo "Script found ✅"
          } else {
            echo "❌ Script not found at $env:SCRIPT_PATH"
            exit 1
          }

      - name: Set Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process

      - name: Run PowerShell Script
        run: |
          echo "Executing script: $env:SCRIPT_PATH"
          & $env:SCRIPT_PATH